runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:Yc7t46yXlsdw+KRgOOFhwpcVyrGdOw6HrY49tygYXBM=
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: laravel
  DB_USERNAME: root
  DB_PASSWORD: hzN0uKkKksqBbr7q
  DB_SOCKET: "/cloudsql/puppies-hub:asia-southeast1:puppies-hub-database"

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "puppies-hub:asia-southeast1:puppies-hub-database"
